openapi: 3.0.0
info:
  title: Co-Operative Work Programmming InterfacE
  version: 2.0.0
paths:
  /:
    get:
      responses:
        200:
          description: OK
          content: 
            'application/json;profile=https://acme.com/cow':
              schema:
                $ref: '#/components/schemas/cooperatingWorker'
              examples:
                default:
                  $ref: '#/components/examples/cooperatingWorker'

  /tasks:
    post:
      summary: Assign work to be performed
      parameters:
        - name: prefer
          in: header
          schema: 
            type: string
      requestBody:
        description: Description of the work to be performed
        content: 
          'application/json;profile=http://acme.com/sow': 
            schema:
              $ref: '#/components/schemas/statementOfWork'
            examples:
              default:
                $ref: '#/components/examples/statementOfWork'
      responses:
        201: 
          description: New task created successfully.
          headers:
            Content-Location:
              schema:
                type: string
                format: uri
    get:
      summary: Retreive a list of tasks a service has been asked to perform
      responses:
        200:
          description: A list of tasks a service has been asked to peform
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statementOfWork'
  /tasks/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema: 
            type: string
      responses:
        200:
          description: A document describing a statement of work
          content:
            'application/json;profile=http://acme.com/sow':
              schema:
                $ref: '#/components/schemas/statementOfWork'
              examples:
                default:
                  $ref: '#/components/schemas/statementOfWork'
  /peers:
    post:
      summary: Register peer as available to help with work
      requestBody:
        content:
          'application/json;profile=https://acme.com/schemas/cow':
            schema:
              $ref: '#/components/schemas/cooperatingWorker'
      responses:
        201:
          description: Created peer for work co-ordination
      callbacks:
        createTask:
          '$request.body#/tasksUrl':
            post:
              requestBody:
                content:
                  'application/json:profile=https://acme.com/schemas/sow': 
                    schema:
                      $ref: '#/components/schemas/statementOfWork'
              responses:
                200:
                  description: Work created for peer
        getCapacity:
          '$request.body#/capacityUrl':
            get:
              responses:
                200:
                  description: List of skills and the available capacity
                  content:
                    'application/json;profile=https://acme.com/schemas/statementOfWork':
                      schema:
                        $ref: '#/components/schemas/statementOfWork'
    get:
      responses:
        200:
          description: A list of peers registered to share workload
          content:
            'application/json;profile=http://acme.com/cooperatingWorkerList':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/cooperatingWorker'
  /peers/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema: 
            type: string
      responses:
        200:
          description: A document describing a cooperating worker
          content:
            'application/json;profile=http://acme.com/cow':
              schema:
                $ref: '#/components/schemas/cooperatingWorker'
              examples:
                default:
                  $ref: '#/components/schemas/cooperatingWorker'
  /capacity:
    get:
      responses:
        200:
          description: List of skills and the available capacity
          content:
            'application/json;profile=https://acme.com/schemas/worklist':
              schema:
                $ref: '#/components/schemas/workList'
components:
  schemas:
    statementOfWork:
      type: object
      properties:
        statementOfWork:
          type: array
          items:
            type: object
            properties:
              description:
                type: string
              requiredSkills:
                type: array
                items:
                  type: string
              estimatedWork:
                $ref: '#/components/schemas/workList'
              dueDateTime: 
                type: string
                format: DateTime
              completedWork:
                $ref: '#/components/schemas/workList'
              status:
                enum:
                - Active
                - Completed
                - Waiting
                - Cancelled       
            required: ["description"]
    workItem:
      type: object
      properties:
        skill:
          type: string
        minutes:
          type: number
    workList:
      type: array
      items:
        $ref: '#/components/schemas/workItem'
    cooperatingWorker:
      type: object
      properties:
        skills:
          type: array
          items:
            type: string
        tasksUrl:
          type: string
          format: uri
        capacityUrl:
          type: string
          format: uri          
  examples:
    cooperatingWorker:
      summary:  Information about a worker able to perform work
      value:
        skills:
        - sing
        - dance
        tasksUrl: https://conference.azure-api.net/cow/tasks
        capacityUrl: https://conference.azure-api.net/cow/capacity
    statementOfWork:
      summary: A description of work that needs to be performed
      value:
        description: Do this stuff for me  # Required
        requiredSkills: ["dance","sing","limbo"] # Optional
        estimatedWork: # Optional
          - skill: dance
            minutes: 3
          - skill: sing
            minutes: 7
          - skill: limbo
            minutes: 1
        dueDateTime : "2017-10-22 10:45am" # Optional
        completedWork: 
          - skill: dance
            minutes: 2
        status : Active 
