
@cow=http://localhost:58260/api

### Get List of Tasks
GET {{cow}}/tasks


### Create a task
POST {{cow}}/tasks
Content-Type: application/json

{
    "statementOfWork": [
        { 
            "description":  "Stuff that just needs to be done 3",  
            "requiredSkills": ["dance","sing"], 
            "estimatedWork": [                  
                { "skill" : "dance", "minutes" : 3},
                { "skill": "sing", "minutes": 7}
            ],
            "dueDateTime" : "2017-10-22 10:45am"
        }
    ]
}

### Create a short task
POST {{cow}}/tasks
Content-Type: application/json

{
    "statementOfWork": [
        { 
            "description":  "Real quick task",  
            "estimatedWork": [                  
                { "skill" : "run", "minutes" : 0.5}
            ]
        }
    ]
}

### Get Details of a Task
GET {{cow}}/tasks/2

### Delete a Task
DELETE {{cow}}/tasks/1

